### PR TITLE
Add bypass cache option to query screen

### PR DESCRIPTION
**Pull request by couchand**
This adds an optional checkbox to the query screen to clear the cached results before running a query.

### CODE REVIEW

**Comment by couchand** [comment]
Any thoughts @NickCraver?

**Comment by NickCraver** [comment]
Ah! Sorry, I missed this when it came in (I get a *lot* of GitHub email). The only issue I see is in `ClearCachedResults`, can you re-write this use `DELETE CachedResults WHERE QueryHash = @hash AND SiteId = @site` in a single method instead?

Currently, this would pull back the entire result set from a query (can be 50,000 rows) for the express purpose of throwing it away. On a remote server that can be pretty costly. Collapsing that into a single delete will resolve it - ping when that's done and I'm happy to merge in and deploy the setting on the internal SEDE template.

**Comment by couchand** [comment]
@NickCraver sounds reasonable.  I'll add that in and let you know.

**Comment by couchand** [comment]
@NickCraver should be good, thanks for taking care of this.

**Comment by NickCraver** [comment]
Merged! I'll get the internal instances deployed with this sucker enabled Monday or before!

**Comment by couchand** [comment]
:beers:

**Pull request merged**
